#!/bin/bash
echo ""
read -p "Pagure Git project name to modify : " repo
read -p "Pagure namespace (like 'rpms'): " namespace
read -p "FAS group to grant access: " fas_group
read -p "Which environment (like 'dev'): " config_file

if [ -e ~/.pagure-${config_file}.cfg ] ;then
  source ~/.pagure-${config_file}.cfg
else
  echo "You need to create a ~/.pagure-${config_file}.cfg file with the following settings:"
  echo "pagure_url=    # main url like https://git.dev.centos.org"
  echo "pagure_token=  # your pagure API token for that instance"
  exit 1
fi

curl -H "Authorization: token ${pagure_token}" -H "Content-Type: application/x-www-form-urlencoded" -X POST -d "user_type=group&name=${fas_group}&acl=commit" "${pagure_url}/api/0/${namespace}/${repo}/git/modifyacls"

